### PR TITLE
Use transactions for childpages data processing

### PR DESCRIPTION
**Pull request by mestaritonttu**

### CODE REVIEW

**Comment by mestaritonttu** [comment]
Note that if this is merged, BCE will require PW version 3.0.114 or later. One possibility would be to go with the $this->wire('config')->dbEngine solution, which would work in older versions.

**Comment by adrianbj** [comment]
Thanks - much appreciated.

BCE currently supports back to PW 2.6 so I don't really want to all of a sudden restrict it to a dev version.

I think it makes most sense to replicate the new `supportsTransactions()` method inside BCE and use that if it's not available in the PW core of the version being used. 

Would you mind adjusting the PR to take this approach please?

**Comment by adrianbj** [comment]
I also meant to ask - did you do any testing to see the performance benefits with this implemented?

**Comment by mestaritonttu** [comment]
> I also meant to ask - did you do any testing to see the performance benefits with this implemented?

Yes, the InnoDB transactions breakthrough was achieved by using BCE. I will look into replicating supportsTransactions() later.

**Comment by adrianbj** [comment]
Thanks again for this!

I feel like it probably also needs to be added to my TableCSVImportExport module.

**Comment by mestaritonttu** [comment]
> I feel like it probably also needs to be added to my TableCSVImportExport module.

And https://github.com/ryancramerdesign/ImportPagesCSV :)

**Pull request merged**
