### PR TITLE
Overwrite mode needs to adjust for `ignoreFirstRow` as well.

### PR DESCRIPTION
**Pull request by LostKobrakai**

### CODE REVIEW

**Comment by adrianbj** [comment]
Thanks - I'll look at this shortly. 

I am working on the overwrite mode as we speak - changing things so it's possible to not have a title field pairing defined which should make updates to data on pages much more flexible - stay tuned!

**Comment by LostKobrakai** [comment]
I will. I'm right now working on a project which relies very much on an offline excel-sheet. That's how I get to find such issues :smile:.

**Comment by adrianbj** [comment]
Thanks again, your changes have been incorporated, but I couldn't accept the PR because I had already moved a few blocks around in that section of code.

**Comment by adrianbj** [comment]
PS Please let me know how the module is working for you and if you can think of any changes that would help. I would like to push dev to master fairly shortly, but having some feedback and some more real world testing would be great since there have been so many major changes.

Thanks!

**Comment by LostKobrakai** [comment]
One small suggestion: The config page is quite a beast. Maybe the page could benefit from some fieldsets, e.g. Mode Settings, CSV Settings and Descriptions?

**Comment by LostKobrakai** [comment]
~~And I get an error, when I try to save the settings after copying over your updates.~~

Nevermind reinstalling solved the issue.

**Comment by LostKobrakai** [comment]
But I get an similar error when I try to update child pages, too.

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'schulung-2701' for key 'name_parent_id'
#0 …/wire/core/Pages.php(1889): PDOStatement->execute() 
#1 …/wire/core/Pages.php(1114): Pages->executeQuery(Object(PDOStatement)) 
#2 …/wire/core/Pages.php(1019): Pages->savePageQuery(Object(Page), Array) 
#3 [internal function]: Pages->___save(Object(Page), Array) 
#4 …/wire/core/Wire.php(383): call_user_func_array(Array, Array) 
#5 …/wire/core/Wire.php(321): Wire->runHooks('save', Array) 
#6 …/wire/core/Page.php(1397): Wire->__call('save', Array) 
#7 …/wire/core/Page.php(1397): Pages->save(Object(Page), Array) 
#8 …/site/modules/BatchChildEditor/BatchChildEditor.module(799): Page->save() 
#9 …/site/modules/BatchChildEditor/BatchChildEditor.module(617): BatchChildEditor->createPages('madeBrands c-p;...', Object(Page), 105) 
#10 …/wire/core/Wire.php(405): BatchChildEditor->saveChildren(Object(HookEvent)) 
#11 …/wire/core/Wire.php(321): Wire->runHooks('processInput', Array) 
#12 …/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module(250): Wire->__call('processInput', Array) 
#13 …/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module(250): ProcessPageEdit->processInput(Object(InputfieldForm)) 
#14 …/wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module(174): ProcessPageEdit->processSave() 
#15 [internal function]: ProcessPageEdit->___execute() 
```

Another potential pitfall I noticed: With the csv pairing set to "16:title" I can't update titles with the update mode.

**Comment by adrianbj** [comment]
I am not getting any errors along those lines. Could you post a screenshot of your config options and also the CSV you are trying to import - PM if you'd prefer.

**Comment by adrianbj** [comment]
Just to round out this issue (which is actually now a little OT), the duplicate entry error was solved with this commit: c32af6fdb017eb2b7ea778dcfabb1d4fb56cd2cd

**Pull request closed without merging**
